import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"
import { Navbar } from "@/components/egem-ui/Navbar";
import { Container } from "@/components/egem-ui/Container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "e",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <Container className={'grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-6'}> {/*ekran büyük olursa 2-1 grid, küçülürse 1 grid*/}
          {children}
        </Container>

        <Toaster />
      </body>
    </html>
  );
}
